<?php

// $Author: wishcraft $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
// Author: Simon Roberts (AKA wishcraft)                                     //
// URL: http://www.chronolabs.org.au                                         //
// Project: The XOOPS Project                                                //
// ------------------------------------------------------------------------- //
error_reporting(E_ALL);

xoops_loadLanguage('modinfo', 'vod');

$modversion['name'] = _MI_VOD_NAME;
$modversion['version'] = 1.17;
$modversion['releasedate'] = "Sunday: January 29, 2012";
$modversion['description'] = _MI_VOD_DESCRIPTION;
$modversion['author'] = "Wishcraft";
$modversion['credits'] = "Simon Roberts (simon@chronolabs.coop)";
$modversion['help'] = "vod.html";
$modversion['license'] = "Fibredyne Software Licence";
$modversion['official'] = 0;
$modversion['module_status']  = "Stable";
$modversion['image'] = "images/vod_slogo.png";
$modversion['dirname'] = _MI_VOD_DIRNAME;

$modversion['system_menu'] = 1;
$modversion['hasMain'] = 1;
$modversion['website'] = "www.chronolabs.coop";

$modversion['dirmoduleadmin'] = 'Frameworks/moduleclasses';
$modversion['icons16'] = 'Frameworks/moduleclasses/icons/16';
$modversion['icons32'] = 'Frameworks/moduleclasses/icons/32';

$modversion['release_info'] = "Stable 2012/01/29";
$modversion['release_file'] = XOOPS_URL."/modules/vod/docs/changelog.txt";
$modversion['release_date'] = "2012/01/29";

$modversion['author_realname'] = "Simon Roberts";
$modversion['author_website_url'] = "http://www.chronolabs.coop";
$modversion['author_website_name'] = "Chronolabs Cooperative";
$modversion['author_email'] = "simon@chronolabs.coop";
$modversion['demo_site_url'] = "";
$modversion['demo_site_name'] = "";
$modversion['support_site_url'] = "";
$modversion['support_site_name'] = "Fibredyne";
$modversion['submit_bug'] = "";
$modversion['submit_feature'] = "";
$modversion['usenet_group'] = "sci.chronolabs";
$modversion['maillist_announcements'] = "";
$modversion['maillist_bugs'] = "";
$modversion['maillist_features'] = "";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php?op=dashboard";
$modversion['adminmenu'] = "admin/menu.php";

// Main things
$modversion['hasMain'] = 1;

$modversion['onUpdate'] = "include/update.php";
//$modversion['onInstall'] = "include/install.php";
//$modversion['onUninstall'] = "include/uninstall.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$i=0;
$modversion['tables'][$i++] = "vod_cart";
$modversion['tables'][$i++] = "vod_category";
$modversion['tables'][$i++] = "vod_currency";
$modversion['tables'][$i++] = "vod_log";
$modversion['tables'][$i++] = "vod_mimetypes";
$modversion['tables'][$i++] = "vod_sessions";
$modversion['tables'][$i++] = "vod_videos";

// Blocks
$i=0;
$i++;
$modversion['blocks'][$i]['file'] = "vod_block_videos.php";
$modversion['blocks'][$i]['name'] = 'Video Stream' ;
$modversion['blocks'][$i]['description'] = "Shows Video Stream Block";
$modversion['blocks'][$i]['show_func'] = "b_vod_block_videos_show";
$modversion['blocks'][$i]['edit_func'] = "b_vod_block_videos_edit";
$modversion['blocks'][$i]['options'] = "|120px|85px|videos_block_one";
$modversion['blocks'][$i]['template'] = "vod_block_videos.html" ;

// Templates
$i=0;
$i++;
$modversion['templates'][$i]['file'] = 'vod_index.html';
$modversion['templates'][$i]['description'] = 'Main Index for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_videos_list.html';
$modversion['templates'][$i]['description'] = 'Main Index List for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_videos_view.html';
$modversion['templates'][$i]['description'] = 'Main Index View for video';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_category_list.html';
$modversion['templates'][$i]['description'] = 'Main Index List for category';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_category_view.html';
$modversion['templates'][$i]['description'] = 'Main Index View for category';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_cart_view.html';
$modversion['templates'][$i]['description'] = 'Main Index List for cart';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_cart_xpayment_form.html';
$modversion['templates'][$i]['description'] = 'Main Form Checkout too Xpayment for cart';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_iframe.html';
$modversion['templates'][$i]['description'] = 'Main Index for IFrame videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_flash_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_iframe_flash_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_flash_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_block_flash_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index.html_rtmp_videos';
$modversion['templates'][$i]['description'] = 'Main Index Error for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_iframe_rtmp_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_rtmp_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_block_rtmp_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_rtsp_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_iframe_rtsp_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_rtsp_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_block_rtsp_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_ios_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_iframe_ios_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_ios_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_block_ios_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_other_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_iframe_other_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_other_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_block_other_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_silverlight_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_iframe_silverlight_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_silverlight_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_block_silverlight_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_html5_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_iframe_html5_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_html5_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_block_html5_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_http_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_index_iframe_http_videos.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_http_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos';
$i++;
$modversion['templates'][$i]['file'] = 'vod_json_block_http_videos.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Videos Videos for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_videos_edit.html';
$modversion['templates'][$i]['description'] = 'Main control Panel Edit Video';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_videos_list.html';
$modversion['templates'][$i]['description'] = 'Main Control Panel Video List';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_mimetypes_edit.html';
$modversion['templates'][$i]['description'] = 'Main control Panel Edit Mimetypes';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_mimetypes_list.html';
$modversion['templates'][$i]['description'] = 'Main Control Panel Mimetypes List';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_currency_edit.html';
$modversion['templates'][$i]['description'] = 'Main control Panel Edit Currencies';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_currency_list.html';
$modversion['templates'][$i]['description'] = 'Main Control Panel Currencies List';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_sessions_edit.html';
$modversion['templates'][$i]['description'] = 'Main control Panel Edit Cart Sessions';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_sessions_list.html';
$modversion['templates'][$i]['description'] = 'Main Control Panel Cart Sessions List';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_cart_edit.html';
$modversion['templates'][$i]['description'] = 'Main control Panel Edit Cart';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_cart_list.html';
$modversion['templates'][$i]['description'] = 'Main Control Panel Cart List';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_category_edit.html';
$modversion['templates'][$i]['description'] = 'Main control Panel Edit Category';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_category_list.html';
$modversion['templates'][$i]['description'] = 'Main Control Panel Category List';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_useragents_list.html';
$modversion['templates'][$i]['description'] = 'Main Control Panel User Agent List';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_log_list.html';
$modversion['templates'][$i]['description'] = 'Main Control Panel User Agent List';
$i++;
$modversion['templates'][$i]['file'] = 'vod_cpanel_permissions_list.html';
$modversion['templates'][$i]['description'] = 'Main Control Panel User Agent List';

$i=0;
xoops_load('XoopsEditorHandler');
$editor_handler = XoopsEditorHandler::getInstance();
foreach ($editor_handler->getList(false) as $id => $val)
	$options[$val] = $id;
	
$i++;
$modversion['config'][$i]['name'] = 'editor';
$modversion['config'][$i]['title'] = "_MI_VOD_EDITORS";
$modversion['config'][$i]['description'] = "_MI_VOD_EDITORS_DESC";
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'tinymce';
$modversion['config'][$i]['options'] = $options;

$i++;
$modversion['config'][$i]['name'] = 'salt';
$modversion['config'][$i]['title'] = "_MI_VOD_SALT";
$modversion['config'][$i]['description'] = "_MI_VOD_SALT_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
mt_srand();
$modversion['config'][$i]['default'] = (mt_rand(0,4)!=2?chr(mt_rand(32,190)):'').(mt_rand(0,4)!=2?chr(mt_rand(32,190)):'').(mt_rand(0,4)!=2?chr(mt_rand(32,190)):'').(mt_rand(0,4)!=2?chr(mt_rand(32,190)):'').(mt_rand(0,4)!=2?chr(mt_rand(32,190)):'').(mt_rand(0,4)!=2?chr(mt_rand(32,190)):'').(mt_rand(0,4)!=2?chr(mt_rand(32,190)):'').(mt_rand(0,4)!=2?chr(mt_rand(32,190)):'').(mt_rand(0,4)!=2?chr(mt_rand(32,190)):'').(mt_rand(0,4)!=2?chr(mt_rand(32,190)):'').(mt_rand(0,4)!=2?chr(mt_rand(32,190)):'').(mt_rand(0,4)!=2?chr(mt_rand(32,190)):'').(mt_rand(0,4)!=2?chr(mt_rand(32,190)):'').(mt_rand(0,4)!=2?chr(mt_rand(32,190)):'');
$modversion['config'][$i]['options'] = array();

$i++;
$modversion['config'][$i]['name'] = 'force_jquery';
$modversion['config'][$i]['title'] = "_MI_VOD_FORCE_JQUERY";
$modversion['config'][$i]['description'] = "_MI_VOD_FORCE_JQUERY_DESC";
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = false;
$modversion['config'][$i]['options'] = array();

$i++;
$modversion['config'][$i]['name'] = 'iframe';
$modversion['config'][$i]['title'] = "_MI_VOD_IFRAME";
$modversion['config'][$i]['description'] = "_MI_VOD_IFRAME_DESC";
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = false;
$modversion['config'][$i]['options'] = array();

$i++;
$modversion['config'][$i]['name'] = 'passkey_diff';
$modversion['config'][$i]['title'] = "_MI_VOD_PASSKEY_DIFF";
$modversion['config'][$i]['description'] = "_MI_VOD_PASSKEY_DIFF_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 40;
$modversion['config'][$i]['options'] = array();

$i++;
$modversion['config'][$i]['name'] = 'passkey_weight';
$modversion['config'][$i]['title'] = "_MI_VOD_PASSKEY_WEIGHT";
$modversion['config'][$i]['description'] = "_MI_VOD_PASSKEY_WEIGHT_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 60;
$modversion['config'][$i]['options'] = array();

$i++;
$modversion['config'][$i]['name'] =  'rtmp_agents';
$modversion['config'][$i]['title'] = '_MI_VOD_RTMP_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_VOD_RTMP_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '(KHTML, like Gecko) Chrome|Firefox|Firebird|SeaMonkey|MSIE|Navigator|Netscape|Opera';

$i++;
$modversion['config'][$i]['name'] =  'flash_agents';
$modversion['config'][$i]['title'] = '_MI_VOD_FLASH_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_VOD_FLASH_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '(KHTML, like Gecko) Chrome|Firefox|Firebird|SeaMonkey|MSIE|Navigator|Netscape|Opera';

$i++;
$modversion['config'][$i]['name'] =  'ios_agents';
$modversion['config'][$i]['title'] = '_MI_VOD_IOS_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_VOD_IOS_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'Safari|Mozilla/5.0 (iPhone; CPU iPhone OS 5_0_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A405 Safari/7534.48.3|Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; es-es) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405|Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; es-es) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B405 Safari/531.21.10|Mozilla/5.0 (iPad; U; CPU OS 3_2_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B500 Safari/531.21.10|Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B367 Safari/531.21.10|Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B367 Safari/531.21.10|Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_1_2 like Mac OS X; en-us) AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7D11 Safari/528.16|Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us) AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7A341 Safari/528.16|Mozilla/5.0 (iPhone; U; CPU like Mac OS X; en) AppleWebKit/420+ (KHTML, like Gecko) Version/3.0 Mobile/1A543a Safari/419.3\')|Mozilla/5.0 (iPad; U; CPU OS 4_3 like Mac OS X; de-de) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8F191 Safari/6533.18.5|Mozilla/5.0 (iPad; U; CPU OS 4_3_1 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8G4 Safari/6533.18.5|Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B334b Safari/531.21.10|Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_8; en-us) AppleWebKit/531.9 (KHTML, like Gecko) Version/4.0.3 Safari/531.9|Mozilla/5.0(iPad; U; CPU iPhone OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B314 Safari/531.21.10|Mozilla/5.0 (iPad; U; CPU OS 4_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8F190 Safari/6533.18.5|Mozilla/5.0 (iPad; CPU OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.0.2 Mobile/9A5248d Safari/6533.18.5\')';

$i++;
$modversion['config'][$i]['name'] =  'silverlight_agents';
$modversion['config'][$i]['title'] = '_MI_VOD_SILVERLIGHT_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_VOD_SILVERLIGHT_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'Media Center PC|Trident|chromeframe|Windows-Media-Videos|MSIE|Firefox';

$i++;
$modversion['config'][$i]['name'] =  'rtsp_agents';
$modversion['config'][$i]['title'] = '_MI_VOD_RTSP_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_VOD_RTSP_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'Android 2.1|Android 2.2|Android 2.2.1|Android 1.0.3|Android 2.2.1|Android 1.6|Android|Fennec';

$i++;
$modversion['config'][$i]['name'] =  'html5_agents';
$modversion['config'][$i]['title'] = '_MI_VOD_HTML5_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_VOD_HTML5_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '(KHTML, like Gecko) Chrome|MSIE';

$i++;
$modversion['config'][$i]['name'] =  'http_agents';
$modversion['config'][$i]['title'] = '_MI_VOD_HTTP_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_VOD_HTTP_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';

$i++;
$modversion['config'][$i]['name'] =  'other_agents';
$modversion['config'][$i]['title'] = '_MI_VOD_OTHER_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_VOD_OTHER_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';

$i++;
$modversion['config'][$i]['name'] =  'speciala_agents';
$modversion['config'][$i]['title'] = '_MI_VOD_SPECIALA_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_VOD_SPECIALA_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';

$i++;
$modversion['config'][$i]['name'] =  'specialb_agents';
$modversion['config'][$i]['title'] = '_MI_VOD_SPECIALB_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_VOD_SPECIALB_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';

include_once(dirname(__FILE__).'/language/'.$GLOBALS['xoopsConfig']['language'].'/modinfo.php');

$i++;
$modversion['config'][$i]['name'] =  'default_videos';
$modversion['config'][$i]['title'] = '_MI_VOD_DEFAULT_VIDEOS';
$modversion['config'][$i]['description'] = '_MI_VOD_DEFAULT_VIDEOS_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'flash';
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_VIDEOS_FLASH')?constant('_MI_VOD_VIDEOS_FLASH'):'Flash Video Videos') => 'flash', (defined('_MI_VOD_VIDEOS_HTML5')?constant('_MI_VOD_VIDEOS_HTML5'):'HTML5 Videos') => 'html5', (defined('_MI_VOD_VIDEOS_IOS')?constant('_MI_VOD_VIDEOS_IOS'):'iOS (Apple) Videos') => 'ios', (defined('_MI_VOD_VIDEOS_RTSP')?constant('_MI_VOD_VIDEOS_RTSP'):'RTSP Videos') => 'rtsp', (defined('_MI_VOD_VIDEOS_RTMP')?constant('_MI_VOD_VIDEOS_RTMP'):'RTMP Videos') => 'rtmp', (defined('_MI_VOD_VIDEOS_SILVERLIGHT')?constant('_MI_VOD_VIDEOS_SILVERLIGHT'):'Silverlight Videos') => 'silverlight', (defined('_MI_VOD_VIDEOS_HTTP')?constant('_MI_VOD_VIDEOS_HTTP'):'HTTP(s) Videos') => 'http', (defined('_MI_VOD_VIDEOS_OTHER')?constant('_MI_VOD_VIDEOS_OTHER'):'Other Videos') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'rtmp_videos';
$modversion['config'][$i]['title'] = '_MI_VOD_RTMP_VIDEOS';
$modversion['config'][$i]['description'] = '_MI_VOD_RTMP_VIDEOS_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'rtmp';
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_VIDEOS_FLASH')?constant('_MI_VOD_VIDEOS_FLASH'):'Flash Video Videos') => 'flash', (defined('_MI_VOD_VIDEOS_HTML5')?constant('_MI_VOD_VIDEOS_HTML5'):'HTML5 Videos') => 'html5', (defined('_MI_VOD_VIDEOS_IOS')?constant('_MI_VOD_VIDEOS_IOS'):'iOS (Apple) Videos') => 'ios', (defined('_MI_VOD_VIDEOS_RTSP')?constant('_MI_VOD_VIDEOS_RTSP'):'RTSP Videos') => 'rtsp', (defined('_MI_VOD_VIDEOS_RTMP')?constant('_MI_VOD_VIDEOS_RTMP'):'RTMP Videos') => 'rtmp', (defined('_MI_VOD_VIDEOS_SILVERLIGHT')?constant('_MI_VOD_VIDEOS_SILVERLIGHT'):'Silverlight Videos') => 'silverlight', (defined('_MI_VOD_VIDEOS_HTTP')?constant('_MI_VOD_VIDEOS_HTTP'):'HTTP(s) Videos') => 'http', (defined('_MI_VOD_VIDEOS_OTHER')?constant('_MI_VOD_VIDEOS_OTHER'):'Other Videos') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'flash_videos';
$modversion['config'][$i]['title'] = '_MI_VOD_FLASH_VIDEOS';
$modversion['config'][$i]['description'] = '_MI_VOD_FLASH_VIDEOS_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'flash';
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_VIDEOS_FLASH')?constant('_MI_VOD_VIDEOS_FLASH'):'Flash Video Videos') => 'flash', (defined('_MI_VOD_VIDEOS_HTML5')?constant('_MI_VOD_VIDEOS_HTML5'):'HTML5 Videos') => 'html5', (defined('_MI_VOD_VIDEOS_IOS')?constant('_MI_VOD_VIDEOS_IOS'):'iOS (Apple) Videos') => 'ios', (defined('_MI_VOD_VIDEOS_RTSP')?constant('_MI_VOD_VIDEOS_RTSP'):'RTSP Videos') => 'rtsp', (defined('_MI_VOD_VIDEOS_RTMP')?constant('_MI_VOD_VIDEOS_RTMP'):'RTMP Videos') => 'rtmp', (defined('_MI_VOD_VIDEOS_SILVERLIGHT')?constant('_MI_VOD_VIDEOS_SILVERLIGHT'):'Silverlight Videos') => 'silverlight', (defined('_MI_VOD_VIDEOS_HTTP')?constant('_MI_VOD_VIDEOS_HTTP'):'HTTP(s) Videos') => 'http', (defined('_MI_VOD_VIDEOS_OTHER')?constant('_MI_VOD_VIDEOS_OTHER'):'Other Videos') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'ios_videos';
$modversion['config'][$i]['title'] = '_MI_VOD_IOS_VIDEOS';
$modversion['config'][$i]['description'] = '_MI_VOD_IOS_VIDEOS_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'ios';
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_VIDEOS_FLASH')?constant('_MI_VOD_VIDEOS_FLASH'):'Flash Video Videos') => 'flash', (defined('_MI_VOD_VIDEOS_HTML5')?constant('_MI_VOD_VIDEOS_HTML5'):'HTML5 Videos') => 'html5', (defined('_MI_VOD_VIDEOS_IOS')?constant('_MI_VOD_VIDEOS_IOS'):'iOS (Apple) Videos') => 'ios', (defined('_MI_VOD_VIDEOS_RTSP')?constant('_MI_VOD_VIDEOS_RTSP'):'RTSP Videos') => 'rtsp', (defined('_MI_VOD_VIDEOS_RTMP')?constant('_MI_VOD_VIDEOS_RTMP'):'RTMP Videos') => 'rtmp', (defined('_MI_VOD_VIDEOS_SILVERLIGHT')?constant('_MI_VOD_VIDEOS_SILVERLIGHT'):'Silverlight Videos') => 'silverlight', (defined('_MI_VOD_VIDEOS_HTTP')?constant('_MI_VOD_VIDEOS_HTTP'):'HTTP(s) Videos') => 'http', (defined('_MI_VOD_VIDEOS_OTHER')?constant('_MI_VOD_VIDEOS_OTHER'):'Other Videos') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'siverlight_videos';
$modversion['config'][$i]['title'] = '_MI_VOD_SILVERLIGHT_VIDEOS';
$modversion['config'][$i]['description'] = '_MI_VOD_SILVERLIGHT_VIDEOS_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'silverlight';
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_VIDEOS_FLASH')?constant('_MI_VOD_VIDEOS_FLASH'):'Flash Video Videos') => 'flash', (defined('_MI_VOD_VIDEOS_HTML5')?constant('_MI_VOD_VIDEOS_HTML5'):'HTML5 Videos') => 'html5', (defined('_MI_VOD_VIDEOS_IOS')?constant('_MI_VOD_VIDEOS_IOS'):'iOS (Apple) Videos') => 'ios', (defined('_MI_VOD_VIDEOS_RTSP')?constant('_MI_VOD_VIDEOS_RTSP'):'RTSP Videos') => 'rtsp', (defined('_MI_VOD_VIDEOS_RTMP')?constant('_MI_VOD_VIDEOS_RTMP'):'RTMP Videos') => 'rtmp', (defined('_MI_VOD_VIDEOS_SILVERLIGHT')?constant('_MI_VOD_VIDEOS_SILVERLIGHT'):'Silverlight Videos') => 'silverlight', (defined('_MI_VOD_VIDEOS_HTTP')?constant('_MI_VOD_VIDEOS_HTTP'):'HTTP(s) Videos') => 'http', (defined('_MI_VOD_VIDEOS_OTHER')?constant('_MI_VOD_VIDEOS_OTHER'):'Other Videos') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'rtsp_videos';
$modversion['config'][$i]['title'] = '_MI_VOD_RTSP_VIDEOS';
$modversion['config'][$i]['description'] = '_MI_VOD_RTSP_VIDEOS_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'rstp';
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_VIDEOS_FLASH')?constant('_MI_VOD_VIDEOS_FLASH'):'Flash Video Videos') => 'flash', (defined('_MI_VOD_VIDEOS_HTML5')?constant('_MI_VOD_VIDEOS_HTML5'):'HTML5 Videos') => 'html5', (defined('_MI_VOD_VIDEOS_IOS')?constant('_MI_VOD_VIDEOS_IOS'):'iOS (Apple) Videos') => 'ios', (defined('_MI_VOD_VIDEOS_RTSP')?constant('_MI_VOD_VIDEOS_RTSP'):'RTSP Videos') => 'rtsp', (defined('_MI_VOD_VIDEOS_RTMP')?constant('_MI_VOD_VIDEOS_RTMP'):'RTMP Videos') => 'rtmp', (defined('_MI_VOD_VIDEOS_SILVERLIGHT')?constant('_MI_VOD_VIDEOS_SILVERLIGHT'):'Silverlight Videos') => 'silverlight', (defined('_MI_VOD_VIDEOS_HTTP')?constant('_MI_VOD_VIDEOS_HTTP'):'HTTP(s) Videos') => 'http', (defined('_MI_VOD_VIDEOS_OTHER')?constant('_MI_VOD_VIDEOS_OTHER'):'Other Videos') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'html5_videos';
$modversion['config'][$i]['title'] = '_MI_VOD_HTML5_VIDEOS';
$modversion['config'][$i]['description'] = '_MI_VOD_HTML5_VIDEOS_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'html5';
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_VIDEOS_FLASH')?constant('_MI_VOD_VIDEOS_FLASH'):'Flash Video Videos') => 'flash', (defined('_MI_VOD_VIDEOS_HTML5')?constant('_MI_VOD_VIDEOS_HTML5'):'HTML5 Videos') => 'html5', (defined('_MI_VOD_VIDEOS_IOS')?constant('_MI_VOD_VIDEOS_IOS'):'iOS (Apple) Videos') => 'ios', (defined('_MI_VOD_VIDEOS_RTSP')?constant('_MI_VOD_VIDEOS_RTSP'):'RTSP Videos') => 'rtsp', (defined('_MI_VOD_VIDEOS_RTMP')?constant('_MI_VOD_VIDEOS_RTMP'):'RTMP Videos') => 'rtmp', (defined('_MI_VOD_VIDEOS_SILVERLIGHT')?constant('_MI_VOD_VIDEOS_SILVERLIGHT'):'Silverlight Videos') => 'silverlight', (defined('_MI_VOD_VIDEOS_HTTP')?constant('_MI_VOD_VIDEOS_HTTP'):'HTTP(s) Videos') => 'http', (defined('_MI_VOD_VIDEOS_OTHER')?constant('_MI_VOD_VIDEOS_OTHER'):'Other Videos') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'http_videos';
$modversion['config'][$i]['title'] = '_MI_VOD_HTTP_VIDEOS';
$modversion['config'][$i]['description'] = '_MI_VOD_HTTP_VIDEOS_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'http';
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_VIDEOS_FLASH')?constant('_MI_VOD_VIDEOS_FLASH'):'Flash Video Videos') => 'flash', (defined('_MI_VOD_VIDEOS_HTML5')?constant('_MI_VOD_VIDEOS_HTML5'):'HTML5 Videos') => 'html5', (defined('_MI_VOD_VIDEOS_IOS')?constant('_MI_VOD_VIDEOS_IOS'):'iOS (Apple) Videos') => 'ios', (defined('_MI_VOD_VIDEOS_RTSP')?constant('_MI_VOD_VIDEOS_RTSP'):'RTSP Videos') => 'rtsp', (defined('_MI_VOD_VIDEOS_RTMP')?constant('_MI_VOD_VIDEOS_RTMP'):'RTMP Videos') => 'rtmp', (defined('_MI_VOD_VIDEOS_SILVERLIGHT')?constant('_MI_VOD_VIDEOS_SILVERLIGHT'):'Silverlight Videos') => 'silverlight', (defined('_MI_VOD_VIDEOS_HTTP')?constant('_MI_VOD_VIDEOS_HTTP'):'HTTP(s) Videos') => 'http', (defined('_MI_VOD_VIDEOS_OTHER')?constant('_MI_VOD_VIDEOS_OTHER'):'Other Videos') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'other_videos';
$modversion['config'][$i]['title'] = '_MI_VOD_OTHER_VIDEOS';
$modversion['config'][$i]['description'] = '_MI_VOD_OTHER_VIDEOS_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'other';
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_VIDEOS_FLASH')?constant('_MI_VOD_VIDEOS_FLASH'):'Flash Video Videos') => 'flash', (defined('_MI_VOD_VIDEOS_HTML5')?constant('_MI_VOD_VIDEOS_HTML5'):'HTML5 Videos') => 'html5', (defined('_MI_VOD_VIDEOS_IOS')?constant('_MI_VOD_VIDEOS_IOS'):'iOS (Apple) Videos') => 'ios', (defined('_MI_VOD_VIDEOS_RTSP')?constant('_MI_VOD_VIDEOS_RTSP'):'RTSP Videos') => 'rtsp', (defined('_MI_VOD_VIDEOS_RTMP')?constant('_MI_VOD_VIDEOS_RTMP'):'RTMP Videos') => 'rtmp', (defined('_MI_VOD_VIDEOS_SILVERLIGHT')?constant('_MI_VOD_VIDEOS_SILVERLIGHT'):'Silverlight Videos') => 'silverlight', (defined('_MI_VOD_VIDEOS_HTTP')?constant('_MI_VOD_VIDEOS_HTTP'):'HTTP(s) Videos') => 'http', (defined('_MI_VOD_VIDEOS_OTHER')?constant('_MI_VOD_VIDEOS_OTHER'):'Other Videos') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'load_vod';
$modversion['config'][$i]['title'] = '_MI_VOD_LOAD_VOD';
$modversion['config'][$i]['description'] = '_MI_VOD_LOAD_VOD_DESC';
$modversion['config'][$i]['formtype'] = 'select_multi';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = array('flash'=>'flash', 'rtmp'=>'rtmp');
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_VIDEOS_FLASH')?constant('_MI_VOD_VIDEOS_FLASH'):'Flash Video Videos') => 'flash', (defined('_MI_VOD_VIDEOS_HTML5')?constant('_MI_VOD_VIDEOS_HTML5'):'HTML5 Videos') => 'html5', (defined('_MI_VOD_VIDEOS_IOS')?constant('_MI_VOD_VIDEOS_IOS'):'iOS (Apple) Videos') => 'ios', (defined('_MI_VOD_VIDEOS_RTSP')?constant('_MI_VOD_VIDEOS_RTSP'):'RTSP Videos') => 'rtsp', (defined('_MI_VOD_VIDEOS_RTMP')?constant('_MI_VOD_VIDEOS_RTMP'):'RTMP Videos') => 'rtmp', (defined('_MI_VOD_VIDEOS_SILVERLIGHT')?constant('_MI_VOD_VIDEOS_SILVERLIGHT'):'Silverlight Videos') => 'silverlight', (defined('_MI_VOD_VIDEOS_HTTP')?constant('_MI_VOD_VIDEOS_HTTP'):'HTTP(s) Videos') => 'http', (defined('_MI_VOD_VIDEOS_OTHER')?constant('_MI_VOD_VIDEOS_OTHER'):'Other Videos') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'load_videojs';
$modversion['config'][$i]['title'] = '_MI_VOD_LOAD_VIDEOJS';
$modversion['config'][$i]['description'] = '_MI_VOD_LOAD_VIDEOJS_DESC';
$modversion['config'][$i]['formtype'] = 'select_multi';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = array('html5'=>'html5','ios'=>'ios','http'=>'http','rtsp'=>'rtsp');
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_VIDEOS_FLASH')?constant('_MI_VOD_VIDEOS_FLASH'):'Flash Video Videos') => 'flash', (defined('_MI_VOD_VIDEOS_HTML5')?constant('_MI_VOD_VIDEOS_HTML5'):'HTML5 Videos') => 'html5', (defined('_MI_VOD_VIDEOS_IOS')?constant('_MI_VOD_VIDEOS_IOS'):'iOS (Apple) Videos') => 'ios', (defined('_MI_VOD_VIDEOS_RTSP')?constant('_MI_VOD_VIDEOS_RTSP'):'RTSP Videos') => 'rtsp', (defined('_MI_VOD_VIDEOS_RTMP')?constant('_MI_VOD_VIDEOS_RTMP'):'RTMP Videos') => 'rtmp', (defined('_MI_VOD_VIDEOS_SILVERLIGHT')?constant('_MI_VOD_VIDEOS_SILVERLIGHT'):'Silverlight Videos') => 'silverlight', (defined('_MI_VOD_VIDEOS_HTTP')?constant('_MI_VOD_VIDEOS_HTTP'):'HTTP(s) Videos') => 'http', (defined('_MI_VOD_VIDEOS_OTHER')?constant('_MI_VOD_VIDEOS_OTHER'):'Other Videos') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'order_rtmp';
$modversion['config'][$i]['title'] = '_MI_VOD_ORDER_RTMP';
$modversion['config'][$i]['description'] = '_MI_VOD_ORDER_RTMP_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 2;
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_ORDER_1ST')?constant('_MI_VOD_ORDER_1ST'):'First') => 1, (defined('_MI_VOD_ORDER_2ND')?constant('_MI_VOD_ORDER_2ND'):'Second') => 2, (defined('_MI_VOD_ORDER_3RD')?constant('_MI_VOD_ORDER_3RD'):'Third') => 3, (defined('_MI_VOD_ORDER_4TH')?constant('_MI_VOD_ORDER_4TH'):'Forth') => 4, (defined('_MI_VOD_ORDER_5TH')?constant('_MI_VOD_ORDER_5TH'):'Fifth') => 5, (defined('_MI_VOD_ORDER_6TH')?constant('_MI_VOD_ORDER_6TH'):'Sixth') => 6, (defined('_MI_VOD_ORDER_7TH')?constant('_MI_VOD_ORDER_7TH'):'Seventh') => 7, (defined('_MI_VOD_ORDER_8TH')?constant('_MI_VOD_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_flash';
$modversion['config'][$i]['title'] = '_MI_VOD_ORDER_FLASH';
$modversion['config'][$i]['description'] = '_MI_VOD_ORDER_FLASH_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 4;
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_ORDER_1ST')?constant('_MI_VOD_ORDER_1ST'):'First') => 1, (defined('_MI_VOD_ORDER_2ND')?constant('_MI_VOD_ORDER_2ND'):'Second') => 2, (defined('_MI_VOD_ORDER_3RD')?constant('_MI_VOD_ORDER_3RD'):'Third') => 3, (defined('_MI_VOD_ORDER_4TH')?constant('_MI_VOD_ORDER_4TH'):'Forth') => 4, (defined('_MI_VOD_ORDER_5TH')?constant('_MI_VOD_ORDER_5TH'):'Fifth') => 5, (defined('_MI_VOD_ORDER_6TH')?constant('_MI_VOD_ORDER_6TH'):'Sixth') => 6, (defined('_MI_VOD_ORDER_7TH')?constant('_MI_VOD_ORDER_7TH'):'Seventh') => 7, (defined('_MI_VOD_ORDER_8TH')?constant('_MI_VOD_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_ios';
$modversion['config'][$i]['title'] = '_MI_VOD_ORDER_IOS';
$modversion['config'][$i]['description'] = '_MI_VOD_ORDER_IOS_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_ORDER_1ST')?constant('_MI_VOD_ORDER_1ST'):'First') => 1, (defined('_MI_VOD_ORDER_2ND')?constant('_MI_VOD_ORDER_2ND'):'Second') => 2, (defined('_MI_VOD_ORDER_3RD')?constant('_MI_VOD_ORDER_3RD'):'Third') => 3, (defined('_MI_VOD_ORDER_4TH')?constant('_MI_VOD_ORDER_4TH'):'Forth') => 4, (defined('_MI_VOD_ORDER_5TH')?constant('_MI_VOD_ORDER_5TH'):'Fifth') => 5, (defined('_MI_VOD_ORDER_6TH')?constant('_MI_VOD_ORDER_6TH'):'Sixth') => 6, (defined('_MI_VOD_ORDER_7TH')?constant('_MI_VOD_ORDER_7TH'):'Seventh') => 7, (defined('_MI_VOD_ORDER_8TH')?constant('_MI_VOD_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_silverlight';
$modversion['config'][$i]['title'] = '_MI_VOD_ORDER_SILVERLIGHT';
$modversion['config'][$i]['description'] = '_MI_VOD_ORDER_SILVERLIGHT_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 5;
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_ORDER_1ST')?constant('_MI_VOD_ORDER_1ST'):'First') => 1, (defined('_MI_VOD_ORDER_2ND')?constant('_MI_VOD_ORDER_2ND'):'Second') => 2, (defined('_MI_VOD_ORDER_3RD')?constant('_MI_VOD_ORDER_3RD'):'Third') => 3, (defined('_MI_VOD_ORDER_4TH')?constant('_MI_VOD_ORDER_4TH'):'Forth') => 4, (defined('_MI_VOD_ORDER_5TH')?constant('_MI_VOD_ORDER_5TH'):'Fifth') => 5, (defined('_MI_VOD_ORDER_6TH')?constant('_MI_VOD_ORDER_6TH'):'Sixth') => 6, (defined('_MI_VOD_ORDER_7TH')?constant('_MI_VOD_ORDER_7TH'):'Seventh') => 7, (defined('_MI_VOD_ORDER_8TH')?constant('_MI_VOD_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_html5';
$modversion['config'][$i]['title'] = '_MI_VOD_ORDER_HTML5';
$modversion['config'][$i]['description'] = '_MI_VOD_ORDER_HTML5_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 3;
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_ORDER_1ST')?constant('_MI_VOD_ORDER_1ST'):'First') => 1, (defined('_MI_VOD_ORDER_2ND')?constant('_MI_VOD_ORDER_2ND'):'Second') => 2, (defined('_MI_VOD_ORDER_3RD')?constant('_MI_VOD_ORDER_3RD'):'Third') => 3, (defined('_MI_VOD_ORDER_4TH')?constant('_MI_VOD_ORDER_4TH'):'Forth') => 4, (defined('_MI_VOD_ORDER_5TH')?constant('_MI_VOD_ORDER_5TH'):'Fifth') => 5, (defined('_MI_VOD_ORDER_6TH')?constant('_MI_VOD_ORDER_6TH'):'Sixth') => 6, (defined('_MI_VOD_ORDER_7TH')?constant('_MI_VOD_ORDER_7TH'):'Seventh') => 7, (defined('_MI_VOD_ORDER_8TH')?constant('_MI_VOD_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_rtsp';
$modversion['config'][$i]['title'] = '_MI_VOD_ORDER_RTSP';
$modversion['config'][$i]['description'] = '_MI_VOD_ORDER_RTSP_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 6;
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_ORDER_1ST')?constant('_MI_VOD_ORDER_1ST'):'First') => 1, (defined('_MI_VOD_ORDER_2ND')?constant('_MI_VOD_ORDER_2ND'):'Second') => 2, (defined('_MI_VOD_ORDER_3RD')?constant('_MI_VOD_ORDER_3RD'):'Third') => 3, (defined('_MI_VOD_ORDER_4TH')?constant('_MI_VOD_ORDER_4TH'):'Forth') => 4, (defined('_MI_VOD_ORDER_5TH')?constant('_MI_VOD_ORDER_5TH'):'Fifth') => 5, (defined('_MI_VOD_ORDER_6TH')?constant('_MI_VOD_ORDER_6TH'):'Sixth') => 6, (defined('_MI_VOD_ORDER_7TH')?constant('_MI_VOD_ORDER_7TH'):'Seventh') => 7, (defined('_MI_VOD_ORDER_8TH')?constant('_MI_VOD_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_http';
$modversion['config'][$i]['title'] = '_MI_VOD_ORDER_HTTP';
$modversion['config'][$i]['description'] = '_MI_VOD_ORDER_HTTP_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 7;
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_ORDER_1ST')?constant('_MI_VOD_ORDER_1ST'):'First') => 1, (defined('_MI_VOD_ORDER_2ND')?constant('_MI_VOD_ORDER_2ND'):'Second') => 2, (defined('_MI_VOD_ORDER_3RD')?constant('_MI_VOD_ORDER_3RD'):'Third') => 3, (defined('_MI_VOD_ORDER_4TH')?constant('_MI_VOD_ORDER_4TH'):'Forth') => 4, (defined('_MI_VOD_ORDER_5TH')?constant('_MI_VOD_ORDER_5TH'):'Fifth') => 5, (defined('_MI_VOD_ORDER_6TH')?constant('_MI_VOD_ORDER_6TH'):'Sixth') => 6, (defined('_MI_VOD_ORDER_7TH')?constant('_MI_VOD_ORDER_7TH'):'Seventh') => 7, (defined('_MI_VOD_ORDER_8TH')?constant('_MI_VOD_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_other';
$modversion['config'][$i]['title'] = '_MI_VOD_ORDER_OTHER';
$modversion['config'][$i]['description'] = '_MI_VOD_ORDER_OTHER_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 8;
$modversion['config'][$i]['options'] = array((defined('_MI_VOD_ORDER_1ST')?constant('_MI_VOD_ORDER_1ST'):'First') => 1, (defined('_MI_VOD_ORDER_2ND')?constant('_MI_VOD_ORDER_2ND'):'Second') => 2, (defined('_MI_VOD_ORDER_3RD')?constant('_MI_VOD_ORDER_3RD'):'Third') => 3, (defined('_MI_VOD_ORDER_4TH')?constant('_MI_VOD_ORDER_4TH'):'Forth') => 4, (defined('_MI_VOD_ORDER_5TH')?constant('_MI_VOD_ORDER_5TH'):'Fifth') => 5, (defined('_MI_VOD_ORDER_6TH')?constant('_MI_VOD_ORDER_6TH'):'Sixth') => 6, (defined('_MI_VOD_ORDER_7TH')?constant('_MI_VOD_ORDER_7TH'):'Seventh') => 7, (defined('_MI_VOD_ORDER_8TH')?constant('_MI_VOD_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'rtmp_secure';
$modversion['config'][$i]['title'] = '_MI_VOD_RTMP_VIDEOS_SECURE';
$modversion['config'][$i]['description'] = '_MI_VOD_RTMP_VIDEOS_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'flash_secure';
$modversion['config'][$i]['title'] = '_MI_VOD_FLASH_VIDEOS_SECURE';
$modversion['config'][$i]['description'] = '_MI_VOD_FLASH_VIDEOS_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'ios_secure';
$modversion['config'][$i]['title'] = '_MI_VOD_IOS_VIDEOS_SECURE';
$modversion['config'][$i]['description'] = '_MI_VOD_IOS_VIDEOS_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'silverlight_secure';
$modversion['config'][$i]['title'] = '_MI_VOD_SILVERLIGHT_VIDEOS_SECURE';
$modversion['config'][$i]['description'] = '_MI_VOD_SILVERLIGHT_VIDEOS_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'rtsp_secure';
$modversion['config'][$i]['title'] = '_MI_VOD_RTSP_VIDEOS_SECURE';
$modversion['config'][$i]['description'] = '_MI_VOD_RTSP_VIDEOS_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'html5_secure';
$modversion['config'][$i]['title'] = '_MI_VOD_HTML5_VIDEOS_SECURE';
$modversion['config'][$i]['description'] = '_MI_VOD_HTML5_VIDEOS_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'http_secure';
$modversion['config'][$i]['title'] = '_MI_VOD_HTTP_VIDEOS_SECURE';
$modversion['config'][$i]['description'] = '_MI_VOD_HTTP_VIDEOS_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'other_secure';
$modversion['config'][$i]['title'] = '_MI_VOD_OTHER_VIDEOS_SECURE';
$modversion['config'][$i]['description'] = '_MI_VOD_OTHER_VIDEOS_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] = 'filesize_upload';
$modversion['config'][$i]['title'] = "_MI_VOD_FILESIZEUPLD";
$modversion['config'][$i]['description'] = "_MI_VOD_FILESIZEUPLD_DESC";
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '1950351';

$i++;
$modversion['config'][$i]['name'] = 'allowed_mimetype';
$modversion['config'][$i]['title'] = "_MI_VOD_ALLOWEDMIMETYPE";
$modversion['config'][$i]['description'] = "_MI_VOD_ALLOWEDMIMETYPE_DESC";
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'image/gif|image/pjpeg|image/jpeg|image/x-png|image/png';

$i++;
$modversion['config'][$i]['name'] = 'allowed_extensions';
$modversion['config'][$i]['title'] = "_MI_VOD_ALLOWEDEXTENSIONS";
$modversion['config'][$i]['description'] = "_MI_VOD_ALLOWEDEXTENSIONS_DESC";
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'gif|pjpeg|jpeg|jpg|png';

$i++;
$modversion['config'][$i]['name'] = 'upload_areas';
$modversion['config'][$i]['title'] = "_MI_VOD_UPLOADAREAS";
$modversion['config'][$i]['description'] = "_MI_VOD_UPLOADAREAS_DESC";
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'uploads'.DS.'vod'.DS;
$modversion['config'][$i]['options'] = array(
												'uploads'.DS => 'uploads'.DS,
												'uploads'.DS.'vod'.DS => 'uploads'.DS.'vod'.DS
										);
$i++;
$modversion['config'][$i]['name'] = 'cat_per_row';
$modversion['config'][$i]['title'] = "_MI_VOD_CAT_PER_ROW";
$modversion['config'][$i]['description'] = "_MI_VOD_CAT_PER_ROW_DESC";
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '3';

$i++;
$modversion['config'][$i]['name'] = 'check_rates';
$modversion['config'][$i]['title'] = '_MI_VOD_CHECK_RATES';
$modversion['config'][$i]['description'] = '_MI_VOD_CHECK_RATES_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = (60*60);
if (defined('_MI_VOD_TIMES_15MINUTES')) {
	$modversion['config'][$i]['options'] = array(_MI_VOD_TIMES_15MINUTES => (60*15), _MI_VOD_TIMES_30MINUTES => (60*30), _MI_VOD_TIMES_45MINUTES => (60*45), 
												 _MI_VOD_TIMES_60MIUNTES => (60*60), _MI_VOD_TIMES_85MINUTES => (60*85), _MI_VOD_TIMES_110MINUTES => (60*110), 
												 _MI_VOD_TIMES_135MINUTES => (60*135), _MI_VOD_TIMES_150MINUTES => (60*150), _MI_VOD_TIMES_180MINUTES => (60*180),
												 _MI_VOD_TIMES_360MINUTES => (360*60), _MI_VOD_TIMES_540MINUTES => (60*540), _MI_VOD_TIMES_900MINUTES => (60*900),
												 _MI_VOD_TIMES_24HOURS => (60*60*24), _MI_VOD_TIMES_48HOURS => (60*60*48), _MI_VOD_TIMES_72HOURS => (60*60*72), 
												 _MI_VOD_TIMES_96HOURS => (60*60*96), _MI_VOD_TIMES_1WEEK => (60*60*24*7), _MI_VOD_TIMES_FORTNIGHT => (60*60*24*7*2), 
												 _MI_VOD_TIMES_1MONTH => (60*60*24*7*4*1), _MI_VOD_TIMES_2MONTHS => (60*60*24*7*4*2), _MI_VOD_TIMES_3MONTHS => (60*60*24*7*4*3), 
												 _MI_VOD_TIMES_4MONTHS => (60*60*24*7*4*4), _MI_VOD_TIMES_5MONTHS => (60*60*24*7*4*5), _MI_VOD_TIMES_6MONTHS => (60*60*24*7*4*6),
												 _MI_VOD_TIMES_12MONTHS => (60*60*24*7*4*12), _MI_VOD_TIMES_24MONTHS => (60*60*24*7*4*24));
}

$i++;
$modversion['config'][$i]['name'] = 'log_cache';
$modversion['config'][$i]['title'] = '_MI_VOD_LOG_CACHE';
$modversion['config'][$i]['description'] = '_MI_VOD_LOG_CACHE_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = (60*60*24*7*2);
if (defined('_MI_VOD_TIMES_15MINUTES')) {
	$modversion['config'][$i]['options'] = array(_MI_VOD_TIMES_15MINUTES => (60*15), _MI_VOD_TIMES_30MINUTES => (60*30), _MI_VOD_TIMES_45MINUTES => (60*45), 
												 _MI_VOD_TIMES_60MIUNTES => (60*60), _MI_VOD_TIMES_85MINUTES => (60*85), _MI_VOD_TIMES_110MINUTES => (60*110), 
												 _MI_VOD_TIMES_135MINUTES => (60*135), _MI_VOD_TIMES_150MINUTES => (60*150), _MI_VOD_TIMES_180MINUTES => (60*180),
												 _MI_VOD_TIMES_360MINUTES => (360*60), _MI_VOD_TIMES_540MINUTES => (60*540), _MI_VOD_TIMES_900MINUTES => (60*900),
												 _MI_VOD_TIMES_24HOURS => (60*60*24), _MI_VOD_TIMES_48HOURS => (60*60*48), _MI_VOD_TIMES_72HOURS => (60*60*72), 
												 _MI_VOD_TIMES_96HOURS => (60*60*96), _MI_VOD_TIMES_1WEEK => (60*60*24*7), _MI_VOD_TIMES_FORTNIGHT => (60*60*24*7*2), 
												 _MI_VOD_TIMES_1MONTH => (60*60*24*7*4*1), _MI_VOD_TIMES_2MONTHS => (60*60*24*7*4*2), _MI_VOD_TIMES_3MONTHS => (60*60*24*7*4*3), 
												 _MI_VOD_TIMES_4MONTHS => (60*60*24*7*4*4), _MI_VOD_TIMES_5MONTHS => (60*60*24*7*4*5), _MI_VOD_TIMES_6MONTHS => (60*60*24*7*4*6),
												 _MI_VOD_TIMES_12MONTHS => (60*60*24*7*4*12), _MI_VOD_TIMES_24MONTHS => (60*60*24*7*4*24));
}

$i++;
$modversion['config'][$i]['name'] = 'purchase_expires';
$modversion['config'][$i]['title'] = '_MI_VOD_PURCHASE_EXPIRES';
$modversion['config'][$i]['description'] = '_MI_VOD_PURCHASE_EXPIRES_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = (60*60*48);
if (defined('_MI_VOD_TIMES_15MINUTES')) {
	$modversion['config'][$i]['options'] = array(_MI_VOD_TIMES_15MINUTES => (60*15), _MI_VOD_TIMES_30MINUTES => (60*30), _MI_VOD_TIMES_45MINUTES => (60*45), 
												 _MI_VOD_TIMES_60MIUNTES => (60*60), _MI_VOD_TIMES_85MINUTES => (60*85), _MI_VOD_TIMES_110MINUTES => (60*110), 
												 _MI_VOD_TIMES_135MINUTES => (60*135), _MI_VOD_TIMES_150MINUTES => (60*150), _MI_VOD_TIMES_180MINUTES => (60*180),
												 _MI_VOD_TIMES_360MINUTES => (360*60), _MI_VOD_TIMES_540MINUTES => (60*540), _MI_VOD_TIMES_900MINUTES => (60*900),
												 _MI_VOD_TIMES_24HOURS => (60*60*24), _MI_VOD_TIMES_48HOURS => (60*60*48), _MI_VOD_TIMES_72HOURS => (60*60*72), 
												 _MI_VOD_TIMES_96HOURS => (60*60*96), _MI_VOD_TIMES_1WEEK => (60*60*24*7), _MI_VOD_TIMES_FORTNIGHT => (60*60*24*7*2), 
												 _MI_VOD_TIMES_1MONTH => (60*60*24*7*4*1), _MI_VOD_TIMES_2MONTHS => (60*60*24*7*4*2), _MI_VOD_TIMES_3MONTHS => (60*60*24*7*4*3), 
												 _MI_VOD_TIMES_4MONTHS => (60*60*24*7*4*4), _MI_VOD_TIMES_5MONTHS => (60*60*24*7*4*5), _MI_VOD_TIMES_6MONTHS => (60*60*24*7*4*6),
												 _MI_VOD_TIMES_12MONTHS => (60*60*24*7*4*12), _MI_VOD_TIMES_24MONTHS => (60*60*24*7*4*24));
}

$i++;
$modversion['config'][$i]['name'] = 'cart_expires';
$modversion['config'][$i]['title'] = '_MI_VOD_CART_EXPIRES';
$modversion['config'][$i]['description'] = '_MI_VOD_CART_EXPIRES_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = (60*60*24*7);
if (defined('_MI_VOD_TIMES_15MINUTES')) {
	$modversion['config'][$i]['options'] = array(_MI_VOD_TIMES_15MINUTES => (60*15), _MI_VOD_TIMES_30MINUTES => (60*30), _MI_VOD_TIMES_45MINUTES => (60*45), 
												 _MI_VOD_TIMES_60MIUNTES => (60*60), _MI_VOD_TIMES_85MINUTES => (60*85), _MI_VOD_TIMES_110MINUTES => (60*110), 
												 _MI_VOD_TIMES_135MINUTES => (60*135), _MI_VOD_TIMES_150MINUTES => (60*150), _MI_VOD_TIMES_180MINUTES => (60*180),
												 _MI_VOD_TIMES_360MINUTES => (360*60), _MI_VOD_TIMES_540MINUTES => (60*540), _MI_VOD_TIMES_900MINUTES => (60*900),
												 _MI_VOD_TIMES_24HOURS => (60*60*24), _MI_VOD_TIMES_48HOURS => (60*60*48), _MI_VOD_TIMES_72HOURS => (60*60*72), 
												 _MI_VOD_TIMES_96HOURS => (60*60*96), _MI_VOD_TIMES_1WEEK => (60*60*24*7), _MI_VOD_TIMES_FORTNIGHT => (60*60*24*7*2), 
												 _MI_VOD_TIMES_1MONTH => (60*60*24*7*4*1), _MI_VOD_TIMES_2MONTHS => (60*60*24*7*4*2), _MI_VOD_TIMES_3MONTHS => (60*60*24*7*4*3), 
												 _MI_VOD_TIMES_4MONTHS => (60*60*24*7*4*4), _MI_VOD_TIMES_5MONTHS => (60*60*24*7*4*5), _MI_VOD_TIMES_6MONTHS => (60*60*24*7*4*6),
												 _MI_VOD_TIMES_12MONTHS => (60*60*24*7*4*12), _MI_VOD_TIMES_24MONTHS => (60*60*24*7*4*24));
}
$i++;
$modversion['config'][$i]['name'] = 'cart_deleted';
$modversion['config'][$i]['title'] = '_MI_VOD_CART_DELETED';
$modversion['config'][$i]['description'] = '_MI_VOD_CART_DELETED_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = (60*60*24*7*4*6);
if (defined('_MI_VOD_TIMES_15MINUTES')) {
	$modversion['config'][$i]['options'] = array(_MI_VOD_TIMES_15MINUTES => (60*15), _MI_VOD_TIMES_30MINUTES => (60*30), _MI_VOD_TIMES_45MINUTES => (60*45), 
												 _MI_VOD_TIMES_60MIUNTES => (60*60), _MI_VOD_TIMES_85MINUTES => (60*85), _MI_VOD_TIMES_110MINUTES => (60*110), 
												 _MI_VOD_TIMES_135MINUTES => (60*135), _MI_VOD_TIMES_150MINUTES => (60*150), _MI_VOD_TIMES_180MINUTES => (60*180),
												 _MI_VOD_TIMES_360MINUTES => (360*60), _MI_VOD_TIMES_540MINUTES => (60*540), _MI_VOD_TIMES_900MINUTES => (60*900),
												 _MI_VOD_TIMES_24HOURS => (60*60*24), _MI_VOD_TIMES_48HOURS => (60*60*48), _MI_VOD_TIMES_72HOURS => (60*60*72), 
												 _MI_VOD_TIMES_96HOURS => (60*60*96), _MI_VOD_TIMES_1WEEK => (60*60*24*7), _MI_VOD_TIMES_FORTNIGHT => (60*60*24*7*2), 
												 _MI_VOD_TIMES_1MONTH => (60*60*24*7*4*1), _MI_VOD_TIMES_2MONTHS => (60*60*24*7*4*2), _MI_VOD_TIMES_3MONTHS => (60*60*24*7*4*3), 
												 _MI_VOD_TIMES_4MONTHS => (60*60*24*7*4*4), _MI_VOD_TIMES_5MONTHS => (60*60*24*7*4*5), _MI_VOD_TIMES_6MONTHS => (60*60*24*7*4*6),
												 _MI_VOD_TIMES_12MONTHS => (60*60*24*7*4*12), _MI_VOD_TIMES_24MONTHS => (60*60*24*7*4*24));
}
											 
$currency_handler = xoops_getmodulehandler('currency', 'vod');
if ($currency_handler->getCount(NULL)==0) {
	$options = Array('Australian Dollar (AUD)' => 'AUD','American Dollar (USD)' => 'USD', 'Great British Pound (GBP)' => 'GBP', 'Euro (EUR)' => 'EUR');   
} else {
	$options = array();
	foreach($currency_handler->getObjects(NULL) as $id => $currency) {
		$options[$currency->getVar('name'). ' ('.$currency->getVar('code').')'] = $currency->getVar('code');
	}
}
$i++;
$modversion['config'][$i]['name'] = 'currency';
$modversion['config'][$i]['title'] = '_MI_VOD_CURRENCY';
$modversion['config'][$i]['description'] = '_MI_VOD_CURRENCY_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'AUD';
$modversion['config'][$i]['options'] = $options;

$i++;
$modversion['config'][$i]['name'] = 'tax';
$modversion['config'][$i]['title'] = '_MI_VOD_TAX';
$modversion['config'][$i]['description'] = '_MI_VOD_TAX_DESC';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '10';
$modversion['config'][$i]['options'] = $options;

$i++;
$modversion['config'][$i]['name'] = 'crontype';
$modversion['config'][$i]['title'] = '_MI_VOD_CRONTYPE';
$modversion['config'][$i]['description'] = '_MI_VOD_CRONTYPE_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'preloader';
if (defined('_MI_VOD_CRONTYPE_PRELOADER')) {
	$modversion['config'][$i]['options'] = 	array(	_MI_VOD_CRONTYPE_PRELOADER => 'preloader', 
													_MI_VOD_CRONTYPE_CRONTAB => 'crontab', 
													_MI_VOD_CRONTYPE_SCHEDULER => 'scheduler'
											);
}

$i++;
$modversion['config'][$i]['name'] = 'interval';
$modversion['config'][$i]['title'] = '_MI_VOD_INTERVAL';
$modversion['config'][$i]['description'] = '_MI_VOD_INTERVAL_DESC';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 300;
$modversion['config'][$i]['options'] = 	array();

$i++;
$modversion['config'][$i]['name'] = 'notify';
$modversion['config'][$i]['title'] = '_MI_VOD_NOTIFY';
$modversion['config'][$i]['description'] = '_MI_VOD_NOTIFY_DESC';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 30;
$modversion['config'][$i]['options'] = 	array();

$i++;
$modversion['config'][$i]['name'] = 'preview_by_default';
$modversion['config'][$i]['title'] = '_MI_VOD_PREVIEW_BY_DEFAULT';
$modversion['config'][$i]['description'] = '_MI_VOD_PREVIEW_BY_DEFAULT_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = true;

$i++;
$modversion['config'][$i]['name'] = 'video_width_main';
$modversion['config'][$i]['title'] = '_MI_VOD_VIDEO_WIDTH_MAIN';
$modversion['config'][$i]['description'] = '_MI_VOD_VIDEO_WIDTH_MAIN_DESC';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '100%';

$i++;
$modversion['config'][$i]['name'] = 'video_height_main';
$modversion['config'][$i]['title'] = '_MI_VOD_VIDEO_HEIGHT_MAIN';
$modversion['config'][$i]['description'] = '_MI_VOD_VIDEO_HEIGHT_MAIN_DESC';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '560px';

$i++;
$modversion['config'][$i]['name'] = 'video_width_list';
$modversion['config'][$i]['title'] = '_MI_VOD_VIDEO_WIDTH_LIST';
$modversion['config'][$i]['description'] = '_MI_VOD_VIDEO_WIDTH_LIST_DESC';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '120px';

$i++;
$modversion['config'][$i]['name'] = 'video_height_list';
$modversion['config'][$i]['title'] = '_MI_VOD_VIDEO_HEIGHT_LIST';
$modversion['config'][$i]['description'] = '_MI_VOD_VIDEO_HEIGHT_LIST_DESC';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '80px';

$i++;
$modversion['config'][$i]['name'] = 'video_width_block';
$modversion['config'][$i]['title'] = '_MI_VOD_VIDEO_WIDTH_BLOCK';
$modversion['config'][$i]['description'] = '_MI_VOD_VIDEO_WIDTH_BLOCK_DESC';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '145px';

$i++;
$modversion['config'][$i]['name'] = 'video_height_block';
$modversion['config'][$i]['title'] = '_MI_VOD_VIDEO_HEIGHT_BLOCK';
$modversion['config'][$i]['description'] = '_MI_VOD_VIDEO_HEIGHT_BLOCK_DESC';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '90px';

$i++;
$modversion['config'][$i]['name'] = 'htaccess';
$modversion['config'][$i]['title'] = "_MI_VOD_HTACCESS";
$modversion['config'][$i]['description'] = "_MI_VOD_HTACCESS_DESC";
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '0';

$i++;
$modversion['config'][$i]['name'] = 'baseofurl';
$modversion['config'][$i]['title'] = "_MI_VOD_HTACCESS_BASEOFURL";
$modversion['config'][$i]['description'] = "_MI_VOD_HTACCESS_BASEOFURL_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'videos';

$i++;
$modversion['config'][$i]['name'] = 'endofurl';
$modversion['config'][$i]['title'] = "_MI_VOD_HTACCESS_ENDOFURL";
$modversion['config'][$i]['description'] = "_MI_VOD_HTACCESS_ENDOFURL_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '.html';

$i++;
$modversion['config'][$i]['name'] = 'matrixstream';
$modversion['config'][$i]['title'] = "_MI_VOD_MATRIXSTREAM";
$modversion['config'][$i]['description'] = "_MI_VOD_MATRIXSTREAM_DESC";
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '0';

$i++;
$modversion['config'][$i]['name'] = 'tags';
$modversion['config'][$i]['title'] = "_MI_VOD_TAGS";
$modversion['config'][$i]['description'] = "_MI_VOD_TAGS_DESC";
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '0';
?>
